### ISSUE TITLE
Only returns the last line of the file

### ISSUE THREAD

**Issue by arisolt** [nickewing/line-reader#13]
The following code:

```
var linereader = require('line-reader');

linereader.eachLine('test_data', function(line, last) {
	console.log(line);
});
```

with `test_data`:

```
aa
bb
cc
dd
```

only returns `dd` in the console.

**Comment by jedwards1211** [comment]
This may have been a line separator issue.  I just contributed a PR that supports line endings from any platform, let me know if that works for the data straight out of Excel.

**Comment by nickewing** [comment]
Tested in current version.  Seems to have been fixed at some point.
