### ISSUE TITLE
Attempting to open a non-existant file hard-crashes Node

### ISSUE THREAD

**Issue by redwood-labs** [nickewing/line-reader#16]
They way the internal `open` function is implemented, it simply throws any error it receives when attempting to open a file.  This is a major problem since that error is in a OS-level callback and therefore can't be handled by the caller.  Basically, a missing file can crash your entire app.

Here's a brief code example which reproduces the problem:
```js
var lineReader = require("line-reader");

try {
    lineReader.eachLine('missing file', function(line, isLast) {
        console.log("got a line: " + line);
    }).then(function () {
        console.log("all done!");
    });
} catch (e) {
    console.log("got an exception: " + e);
}
```

**Comment by scharf** [comment]
The API is not following the node standard, because it does not use `error` as first argument in the callback.

**Comment by jedwards1211** [comment]
I was thinking about this, I think there should just be an `(error, result)` callback after the `(line, last)` callback in the arguments to `eachLine()`, plus the other options should be supplied as a hash that comes before this last callback.  That way the function could be auto-promisified by libraries like bluebird.

I looks to me like Nick Ewing doesn't intend to actively maintain this...but he has merged PRs somewhat recently.

**Comment by nickewing** [comment]
@jedwards1211 You're right, I haven't had time to do fixes myself and I haven't been working with node recently.  I am very happy to review and accept PRs however!

**Comment by jedwards1211** [comment]
Yeah, understandable!  Well if I find time soon I'll see if I can make a PR for this.
