### ISSUE TITLE
Update on npm

### ISSUE THREAD

**Issue by felixSchl** [nickewing/line-reader#28]
Hi,

The version on npm does not work, however the code on `master` does.
I am looking at adding this library as a dependency to my project, any chance the npm package could be updated?

**Comment by felixSchl** [comment]
Please?

**Comment by onury** [comment]
+1

**Comment by nickewing** [comment]
Sorry, I've been on vacation out of the country (and still am) with very little internet access.  I just pushed to npm.

**Comment by felixSchl** [comment]
Thank you for taking the time and enjoy the rest of your vacation :)

**Comment by nickewing** [comment]
No problem.  Should have updated it already anyway. :)
