### ISSUE TITLE
Smart EOL Support

### ISSUE THREAD

**Issue by vy** [nickewing/line-reader#6]
IMHO, hardcoded `\n` should be replaced with `os.EOL`. Further, it would be really handy if line-separator could automatically make a decision between `\n` and `\r\n` by looking at the very first line.

**Comment by jedwards1211** [comment]
Even then you can end up getting files that came from another OS, so I wouldn't recommend that.  I just put in a pull request that uses the regexp `/\r\n?|\n/` by default, so it automatically handles files from any platform correctly.

**Comment by nickewing** [comment]
I'll have to agree with @jedwards1211 on this one.  Thanks to his recent PR, the new default is now `/\r\n?|\n/ `.
