### ISSUE TITLE
errors?

### ISSUE THREAD

**Issue by mark-hahn** [nickewing/line-reader#7]
What happens on an open or read error?  Using the node standard would be nice.  Throwing is not nice in node.

**Comment by jedwards1211** [comment]
Hi Mark, I see it's been two years since you wrote this...did you find a more actively maintained line reader library?

**Comment by mark-hahn** [comment]
No but I haven't been looking.  I've just gotten in the habit of coding my own.

**Comment by jedwards1211** [comment]
I see.  Well probably soon I'll make a PR that passes errors to node-style callbacks.
